### ISSUE TITLE
[Official] Alarm System Block

### ISSUE THREAD

**Issue by northwesttreesgaming** [northwesttrees-gaming/CCTV-Craft#16]
# Overview
A block that can trigger on or off multiple [Sound Blocks](#9 ) at once.

## Features
- Can turn on/off many Sound Blocks at the same time.
- Advancements for placing the Alarm System block.
- Custom block models for both on and off states.
- Has an on/off state that can disable or enable accessing the GUI.
- Custom block name support.
- Permission support for editing the block's connections.
- Toggleable via a new monitor screen.

## Tasks
- [x] Make textures and models for the alarm system block.
- [x] Make advancements for the alarm System
- [x] Make a menu for setting up sound block connections
- [x] Create an on/off state for the alarm system block.
- [x] Make it possible to toggle all connected sound blocks on or off.
- [x] Make it possible to set permissions for the alarm system block.
- [x] Allow custom names for the alarm system block
- [x] Make it possible to use the Name USB on the alarm system block.
- [ ] #24
