### ISSUE TITLE
[Official] Items and Recipes Update

### ISSUE THREAD

**Issue by northwesttreesgaming** [northwesttrees-gaming/CCTV-Craft#20]
# Overview
Update some of the textures for items and block icons as well as clean up recipe groups and make recipes better for crafting.

# Features
- Better crafting recipes
- Better recipe group management
- Better textures for some block and item icons.

# Tasks
- [x] Set better crafting recipes
- [x] Set better recipe groups
- [x] Create and update better items and block textures for icons.
