### ISSUE TITLE
[Official] Aluminum

### ISSUE THREAD

**Issue by northwesttreesgaming** [northwesttrees-gaming/CCTV-Craft#22]
# Overview
Create a new resource that can be controlled by the mod to replace iron in the crafting recipes.

# Features
- New ore block "Aluminum Ore"
- New raw item "Raw Aluminum"
- New ingot "Aluminum Ingot"
- Will be used instead of iron ingots.

## Tasks
- [x] Create an Aluminum Ore block
- [x] Create Raw Aluminum item
- [x] Create an Aluminum Ingot item
- [x] Add blasting and smelting recipes for Aluminum Ingots
- [x] Create a loot table for Aluminum Ore when mined with fortune.
- [x] Update recipes that require iron ingots and replace them with a new resource.
