### ISSUE TITLE
Proximity Scanner

### ISSUE THREAD

**Issue by northwesttreesgaming** [northwesttrees-gaming/CCTV-Craft#5]
# About
Can be used to detect entities or blocks and send a signal to a device of some kind and have a predetermined action to execute eg turn out alarms. It might be possible to route this through the monitor in some way using some kind of card or disk system.

# Core features
- Can detect blocks and entities
- Different textures for each kind of entity or mode.
- New crafting resource for the main block.
- New crafting advancement for the mod.
- New advancement called scanned me.
- Group permissions.

# Tasks to complete
- Can detect entities
  - [ ] Animals
  - [ ] Creatures
  - [ ] Mobs
  - [ ] Monsters
  - [ ] Players
- Can detect specific blocks
  - [ ] A built-in inventory that allows a series of blocks to be tested.
- [ ] Variable updates when the block or entity type is detected.
- [ ] New resources for crafting the block.
- [ ] Advancement for the block.
- [ ] Has ownership settings
- [ ] Different textures based on the action it's performing mob/mob type or block.
