### ISSUE TITLE
[Official] Drone Remastered Update

### ISSUE THREAD

**Issue by northwesttreesgaming** [northwesttrees-gaming/CCTV-Craft#7]
### Discussed in https://github.com/northwesttrees-gaming/CCTV-Craft/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **northwesttreesgaming** March  7, 2023</sup>
This is just a concept at the moment but I would like to eventually make drone entities for smoother flying mechanics.
## Core Features.
- Make drones entities
- Better movement for drones.
- Dynamic camera rotation in camera view mode.
- Drone AI
- Automatic and Controlled Drone Modes.

## Tasks
- [ ] Convert drone models to entities
- [ ] Adjust drone camera script to work with dynamic coordinates
- [ ] Script to make drones stay still when not in use.
- [ ] Rework forge energy system for drones.
- [ ] Make drones able to turn 360 degrees for the camera view.
- [ ] Make drones automatic.
- [ ] Have a drone follow the owner.
- [ ] Make drones shoot enemies that are hostile to the owner.
- [ ] Make it possible to switch between automatic and controlled modes.</div>
