### ISSUE TITLE
[Official] Sound Block

### ISSUE THREAD

**Issue by northwesttreesgaming** [northwesttrees-gaming/CCTV-Craft#9]
# Overview
Alarms will play a selected sound when the block is on. This can be triggered using devices such as proximity sensors or manually turned on using something like an alarm system.

## Features
- When on, the block will play a sound loop.
- Groups of alarms can be linked to Alarm Systems
- Block listens to Alarm Systems when linked to them.
- Block can be triggered with Redstone.
- A few sounds to pick from.
- New crafting resources called speakers for this block.

## Tasks
- [x] Make textures and models for the sound block
- [x] Find some sounds from Freesound's website.
- [x] Make a menu for selecting what sound to play.
- [x] Create an on/off state for the sound block.
- [x] Make it possible to set permissions for the sound block.
- [x] Allow custom names for the sound block
- [x] Make it possible to use the Name USB on the sound block.
- [x] Make advancements for the sound block
- [x] Add a new crafting recipe for the sound block.
- [x] Add a new crafting recipe for the alarm system block.
- [x] Make textures for the new crafting resources.
- [x] Add new recipes for resources.
